spring.application.name=dangerdriving
# 文件上传大小限制 10 MB
spring.servlet.multipart.max-file-size=10MB
# 请求总大小限制 20 MB（包含文件和其他数据）
spring.servlet.multipart.max-request-size=20MB

# Flask API 服务地址配置
flask.api.url=http://localhost:5000
server.port=8082